### PR TITLE
Added Eurus mainnet and testnet network ID.

### PR DESCRIPTION
**Pull request by EU99**

### CODE REVIEW

**Comment by Uxio0** [comment]
We require the networks to be at https://chainlist.org/ before adding

**Comment by EU99** [comment]
> We require the networks to be at https://chainlist.org/ before adding

The networks have already been listed in https://chainlist.org/. Please check Eurus Mainnet(1008) and Eurus Testnet(1984) respectively. Thanks.

**Comment by Uxio0** [comment]
`Eurus Testnet` appears as [BTCIX Network](https://bitcolojix.org/) on chainlist.org

**Comment by EU99** [comment]
I could not find the problem mentioned. Eurus testnet(1984) is displayed normally in chainlist.

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1984.json

**Comment by Uxio0** [comment]
> I could not find the problem mentioned. Eurus testnet(1984) is displayed normally in chainlist.
> 
> https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1984.json

You are right, I missed the `testnet` flag on the website 🤦🏻

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
