### PR TITLE
Adding Velas network mainnet&testnet support

### PR DESCRIPTION
**Pull request by datradito**
Hello @Uxio0 , I'd like to add Velas mainnet &  testnet chains as we work towards Gnosis Safe support.

[https://github.com/ethereum-lists/chains/pull/484](https://github.com/ethereum-lists/chains/pull/484)

Thanks!

### CODE REVIEW

**Comment by datradito** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Uxio0** [comment]
Hi, linting is not passing, please run pre-commit before commiting

**Comment by Uxio0** [comment]
Hi, linting is not passing, please run pre-commit before commiting

**Comment by datradito** [comment]
Hello @Uxio0 , I solved the conflicts.

**Review by Uxio0 — APPROVED** [review]

**Comment by Uxio0** [comment]
@datradito I'm revoming VELAS_TESTNET, as you are already using a taken `chainId` from EtherLite Chain: https://chainlist.org/

**Pull request merged**
